backend:
  name: github
  repo: reikifishuk/reikifish-website
  branch: main
  base_url: https://auth.decapbridge.com
  auth_endpoint: auth

local_backend:
  url: http://127.0.0.1:8081/api/v1
publish_mode: editorial_workflow

media_folder: assets/images/blog
public_folder: /assets/images/blog

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: content/posts
    create: true
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}} - {{date}}"
    fields:
      - { label: Title (H1), name: title, widget: string }
      - { label: Slug, name: slug, widget: string, hint: "Used for article filename, e.g. trauma-recovery" }
      - { label: SEO Title, name: seoTitle, widget: string }
      - { label: Meta Description, name: metaDescription, widget: text }
      - { label: Featured Image, name: featuredImage, widget: image }
      - { label: Featured Image Alt Text, name: featuredImageAlt, widget: string }
      - { label: Categories, name: categories, widget: list, default: [] }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Publish Date, name: date, widget: datetime, format: "YYYY-MM-DD", time_format: false, date_format: "YYYY-MM-DD" }
      - { label: Featured on Blog, name: featured, widget: boolean, required: false, default: false }
      - { label: Draft, name: draft, widget: boolean, required: false, default: true }
      - { label: Author, name: author, widget: string, required: false, default: "Andy Fish" }
      - { label: Excerpt, name: excerpt, widget: text, required: false }
      - label: Content
        name: body
        widget: markdown
        modes: [rich_text, raw]
        editor_components: [image, code-block]
